### ISSUE TITLE
Chain configs (telos-mainnet, telos-testnet, etc..)

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/telos-reth#26]
### Describe the feature

Re-implement the Telos chain config changes from `telos-main-old` to `telos-main` in a single commit.

### Incorporate changes from these commits:

  - [x] a6b9d65e704dd1772888298e3c079c9cdbc1bed3
  - [x] c189ef57d5095ce7d6f8006244dd2b038199bdee
  - [x] 05a4c238e26c05f2f25f44edd2a0b8a149a1c0b9

**Comment by coa-telos** [comment]
Created draft PR #34 with changes from first commit. There are 17 failing tests at the moment, probably due to chain name which fallbacks to id, since name implementaion is in alloy.
