### ISSUE TITLE
Disable the checks for state trie root hash during execution

### ISSUE THREAD

**Issue by aamirpashaa** [telosnetwork/telos-reth#4]
### Describe the feature

Since in Telos EVM, there is no state trie storage, it doesn't have any state trie root hash and in a block, it is set to the default blank value (`0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421`). So the check for validation of state trie root hash should be omitted.

**Comment by poplexity** [comment]
We may want to turn this back on, leaving issue open until that decision is made.

**Comment by poplexity** [comment]
We will not be turning this back on, as block hash needs to be generated/provided by consensus client and it does not have a valid state root to use for generating the hash, it introduces immense complexity and risk.
