### ISSUE TITLE
Gas price function is not returning the fixed gas price

### ISSUE THREAD

**Issue by aamirpashaa** [telosnetwork/telos-reth#74]
The returned gas price should be only the base fee
https://github.com/telosnetwork/telos-reth/blob/0f9605add2ae244f8f8e966eb73e7ca429370c65/crates/rpc/rpc-eth-api/src/helpers/fee.rs#L342-L343

**Comment by poplexity** [comment]
Fixed here: https://github.com/telosnetwork/telos-reth/commit/8c37741ea8d97eba713a8028e3f09132bb51abd6
